[package]
name = "mirth"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tracing = "0.1.37"
tracing-subscriber = "0.3.16"
image = "0.24.4"
cgmath = "0.18.0"
rand_core = "0.6.4"
rand_pcg = "0.3.1"

